image: 'nexus.service.dint.newsaktuell.de:5000/core-backend/images/build-images/openjdk11/mvn-3.8'

variables:
  EMBEDDED_MONGO_CACHE_DIR: ".embeddedMongoCache"

cache:
  - key: "dependencies"
    policy: pull
    when: always
    paths:
      - .m2/
  - key:
      files:
        - pom.xml
    paths:
      - ${LOCAL_CACHE_PATH}

stages:
  - build
  - test
  - after_build

build:
  except:
    - /^release.*$/
    - tags
  stage: build
  tags:
    - scala
  script:
    - 'mvn clean install -DskipTests'
  artifacts:
    paths:
      - '**/target/*'

test:
  stage: test
  except:
    - /^release.*$/
    - tags
  tags:
    - java
  script:
    - 'mvn test --fail-at-end'
  artifacts:
    paths:
      - '**/target/*'
    reports:
      junit:
        - '**/target/surefire-reports/TEST-*.xml'
        - '**/target/failsafe-reports/TEST-*.xml'

#sonar:
#  allow_failure: true
#  stage: after_build
#  cache:
#    policy: pull
#  only:
#    - develop
#  tags:
#    - java
#    - long_running
#  script:
#    - 'mvn sonar:sonar -Dsonar.projectKey=${CI_PROJECT_NAME} -Dsonar.projectName=${CI_PROJECT_NAME}'

push_to_nexus:
  stage: after_build
  except:
    - tags
  cache:
    policy: pull
  tags:
    - java
  only:
    - develop
  script:
    - 'mvn deploy -DskipTests'
