= bannermatik-kt
:doctype: article
:description: Project Documentation for bannermatik-kt
:keywords: figlet, banner, ascii, art, kotlin
:icons: font
:toc:
:toc-title: Contents
:toclevels: 5

== About

For my current team at NA News Aktuell I had to learn the Scala language.
So why not take a fun approach and some nerdy stuff?
As I like colorful banner and back some time have developed a little python tool
to combine https://github.com/pwaller/pyfiglet[pyfiglet] with ANSI banners generated from images I have ported that one into scala.
Hence I was of course not able to leverage pyfiglet this time I had to do a scala port for that as well.
After 3 years now it was time to update this project because in the meantime I had to learn kotlin which
was a much smoother experience after having internalized scala now after some years of practice.
Looking again into your own very old code is always a strange experience and I decided to do yet another rewrite...
So here it is - the kotlin implementation of bannermatik.
To not only having a pure port I added some reverse engineering to implement subpixel rednering for images.

== Usage
